apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: schemas
  labels:
    strimzi.io/cluster: ingest-platform
spec:
  topicName: _schemas
  partitions: 1
  replicas: 3
  config:
    cleanup.policy: compact
    min.insync.replicas: "2"